<a href="https://colab.research.google.com/github/jarrodsb/DSPS_JBieber/blob/main/Labs/Earthquake_data_munging.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Jarrod Bieber - PHYS 461

In [1]:
import pandas as pd

In [2]:
earthquakes = pd.read_csv("https://raw.githubusercontent.com/fedhere/DSPS_FBianco/refs/heads/main/data/earthquakes.csv", sep=r"\s+")

In [3]:
earthquakes.shape

(70798, 13)

In [4]:
earthquakes.head(7)

,#YYY/MM/DD,HH:mm:SS.ss,ET,GT,MAG,M,LAT,LON,DEPTH,Q,EVID,NPH,NGRM
0,1984/01/01,01:30:57.52,eq,l,2.02,c,33.246,-116.433,1.6,C,28255,13,17
1,1984/01/01,05:31:34.16,eq,l,2.12,c,32.945,-116.295,5.4,C,28259,18,42
2,1984/01/01,06:59:05.14,eq,l,2.43,c,33.343,-117.628,5.6,C,28260,13,30
3,1984/01/01,11:10:25.29,eq,l,2.07,c,33.668,-116.780,13.8,C,28270,19,40
4,1984/01/01,19:38:19.79,eq,l,2.13,c,33.963,-116.290,2.7,C,28553,40,49
5,1984/01/01,19:39:19.67,eq,l,2.13,c,34.062,-117.325,18.5,C,28282,32,41
6,1984/01/01,20:19:47.21,eq,l,2.02,c,35.180,-119.016,13.8,C,28284,31,59

In [5]:
earthquakes.tail()

,#YYY/MM/DD,HH:mm:SS.ss,ET,GT,MAG,M,LAT,LON,DEPTH,Q,EVID,NPH,NGRM
70793,2002/12/29,19:37:24.56,eq,l,2.21,l,35.31400,-118.66767,3.7,A,9874709,25,948
70794,2002/12/29,20:17:33.40,eq,l,2.02,l,35.32133,-118.66000,1.8,A,9874745,48,245
70795,2002/12/29,20:21:28.73,eq,l,2.07,l,35.32150,-118.66617,1.9,A,9874749,53,277
70796,2002/12/30,21:51:52.55,eq,l,2.31,l,35.31867,-118.66250,1.5,A,9875017,66,404
70797,2002/12/30,23:38:49.79,eq,l,2.05,l,35.31450,-118.66333,1.9,A,9875061,54,283

In [6]:
earthquakes.columns

Index(['#YYY/MM/DD', 'HH:mm:SS.ss', 'ET', 'GT', 'MAG', 'M', 'LAT', 'LON',
       'DEPTH', 'Q', 'EVID', 'NPH', 'NGRM'],
      dtype='object')

In [7]:
earthquakes[['#YYY/MM/DD', 'HH:mm:SS.ss', "MAG"]]

       #YYY/MM/DD  HH:mm:SS.ss   MAG
0      1984/01/01  01:30:57.52  2.02
1      1984/01/01  05:31:34.16  2.12
2      1984/01/01  06:59:05.14  2.43
3      1984/01/01  11:10:25.29  2.07
4      1984/01/01  19:38:19.79  2.13
...           ...          ...   ...
70793  2002/12/29  19:37:24.56  2.21
70794  2002/12/29  20:17:33.40  2.02
70795  2002/12/29  20:21:28.73  2.07
70796  2002/12/30  21:51:52.55  2.31
70797  2002/12/30  23:38:49.79  2.05

[70798 rows x 3 columns]

In [8]:
earthquakes.dtypes

#YYY/MM/DD      object
HH:mm:SS.ss     object
ET              object
GT              object
MAG            float64
M               object
LAT            float64
LON            float64
DEPTH          float64
Q               object
EVID             int64
NPH              int64
NGRM             int64
dtype: object

In [9]:
mydictionary = {"v1": 0, "v2": 1}
mydictionary["v2"]

1

In [10]:
earthquakes.rename({"#YYY/MM/DD": "date", "HH:mm:SS.ss": "time", "MAG": "mag"}, axis=1)

,date,time,ET,GT,mag,M,LAT,LON,DEPTH,Q,EVID,NPH,NGRM
0,1984/01/01,01:30:57.52,eq,l,2.02,c,33.24600,-116.43300,1.6,C,28255,13,17
1,1984/01/01,05:31:34.16,eq,l,2.12,c,32.94500,-116.29500,5.4,C,28259,18,42
2,1984/01/01,06:59:05.14,eq,l,2.43,c,33.34300,-117.62800,5.6,C,28260,13,30
3,1984/01/01,11:10:25.29,eq,l,2.07,c,33.66800,-116.78000,13.8,C,28270,19,40
4,1984/01/01,19:38:19.79,eq,l,2.13,c,33.96300,-116.29000,2.7,C,28553,40,49
...,...,...,...,...,...,...,...,...,...,...,...,...,...
70793,2002/12/29,19:37:24.56,eq,l,2.21,l,35.31400,-118.66767,3.7,A,9874709,25,948
70794,2002/12/29,20:17:33.40,eq,l,2.02,l,35.32133,-118.66000,1.8,A,9874745,48,245
70795,2002/12/29,20:21:28.73,eq,l,2.07,l,35.32150,-118.66617,1.9,A,9874749,53,277
70796,2002/12/30,21:51:52.55,eq,l,2.31,l,35.31867,-118.66250,1.5,A,9875017,66,404
70797,2002/12/30,23:38:49.79,eq,l,2.05,l,35.31450,-118.66333,1.9,A,9875061,54,283

In [11]:
earthquakes

,#YYY/MM/DD,HH:mm:SS.ss,ET,GT,MAG,M,LAT,LON,DEPTH,Q,EVID,NPH,NGRM
0,1984/01/01,01:30:57.52,eq,l,2.02,c,33.24600,-116.43300,1.6,C,28255,13,17
1,1984/01/01,05:31:34.16,eq,l,2.12,c,32.94500,-116.29500,5.4,C,28259,18,42
2,1984/01/01,06:59:05.14,eq,l,2.43,c,33.34300,-117.62800,5.6,C,28260,13,30
3,1984/01/01,11:10:25.29,eq,l,2.07,c,33.66800,-116.78000,13.8,C,28270,19,40
4,1984/01/01,19:38:19.79,eq,l,2.13,c,33.96300,-116.29000,2.7,C,28553,40,49
...,...,...,...,...,...,...,...,...,...,...,...,...,...
70793,2002/12/29,19:37:24.56,eq,l,2.21,l,35.31400,-118.66767,3.7,A,9874709,25,948
70794,2002/12/29,20:17:33.40,eq,l,2.02,l,35.32133,-118.66000,1.8,A,9874745,48,245
70795,2002/12/29,20:21:28.73,eq,l,2.07,l,35.32150,-118.66617,1.9,A,9874749,53,277
70796,2002/12/30,21:51:52.55,eq,l,2.31,l,35.31867,-118.66250,1.5,A,9875017,66,404
70797,2002/12/30,23:38:49.79,eq,l,2.05,l,35.31450,-118.66333,1.9,A,9875061,54,283

In [12]:
earthquakes = earthquakes.rename({"#YYY/MM/DD": "date", "HH:mm:SS.ss": "time", "MAG": "mag"}, axis=1)

In [13]:
earthquakes

,date,time,ET,GT,mag,M,LAT,LON,DEPTH,Q,EVID,NPH,NGRM
0,1984/01/01,01:30:57.52,eq,l,2.02,c,33.24600,-116.43300,1.6,C,28255,13,17
1,1984/01/01,05:31:34.16,eq,l,2.12,c,32.94500,-116.29500,5.4,C,28259,18,42
2,1984/01/01,06:59:05.14,eq,l,2.43,c,33.34300,-117.62800,5.6,C,28260,13,30
3,1984/01/01,11:10:25.29,eq,l,2.07,c,33.66800,-116.78000,13.8,C,28270,19,40
4,1984/01/01,19:38:19.79,eq,l,2.13,c,33.96300,-116.29000,2.7,C,28553,40,49
...,...,...,...,...,...,...,...,...,...,...,...,...,...
70793,2002/12/29,19:37:24.56,eq,l,2.21,l,35.31400,-118.66767,3.7,A,9874709,25,948
70794,2002/12/29,20:17:33.40,eq,l,2.02,l,35.32133,-118.66000,1.8,A,9874745,48,245
70795,2002/12/29,20:21:28.73,eq,l,2.07,l,35.32150,-118.66617,1.9,A,9874749,53,277
70796,2002/12/30,21:51:52.55,eq,l,2.31,l,35.31867,-118.66250,1.5,A,9875017,66,404
70797,2002/12/30,23:38:49.79,eq,l,2.05,l,35.31450,-118.66333,1.9,A,9875061,54,283

In [14]:
earthquakes.describe()

,mag,LAT,LON,DEPTH,EVID,NPH,NGRM
count,70798.000000,70798.000000,70798.00000,70798.000000,7.079800e+04,70798.000000,70798.000000
mean,2.417826,33.977749,-116.88145,5.707677,3.699163e+06,30.424376,175.725049
std,0.407683,1.156586,1.07667,3.842620,3.495378e+06,22.374143,226.196774
min,2.000000,30.094830,-121.76000,0.000000,2.825500e+04,0.000000,0.000000
25%,2.120000,33.061000,-117.69200,3.100000,7.380962e+05,15.000000,59.000000
50%,2.300000,34.056750,-116.59000,5.300000,3.049477e+06,24.000000,111.000000
75%,2.590000,34.591000,-116.25100,6.900000,3.325926e+06,39.000000,211.000000
max,7.100000,37.985500,-113.71900,29.300000,3.736673e+07,406.000000,3815.000000

In [15]:
pd.to_datetime("2002/12/29" + " " + "19:37:24.56")

Timestamp('2002-12-29 19:37:24.560000')

In [17]:
earthquakes["newdate"] = earthquakes["date"].map(pd.to_datetime)

In [19]:
earthquakes["datetime"] = earthquakes["date"] + " " + earthquakes["time"]

In [20]:
earthquakes["newdatetime"] = earthquakes["datetime"].map(pd.to_datetime)

DateParseError: second must be in 0..59: 1984/08/09 04:48:60.00, at position 0

In [24]:
for i in earthquakes.index:
  if earthquakes.loc[i, "time"].endswith('60.00'):
    print(earthquakes.loc[i, "time"])
    earthquakes.loc[i, "time"] = earthquakes.loc[i, "time"][:6] + "59.99"
    print(earthquakes.loc[i, "time"])

In [25]:
earthquakes["datetime"] = earthquakes["date"] + " " + earthquakes["time"]
earthquakes["newdatetime"] = earthquakes["datetime"].map(pd.to_datetime)

In [26]:
earthquakes["newdatetime"]

0       1984-01-01 01:30:57.520
1       1984-01-01 05:31:34.160
2       1984-01-01 06:59:05.140
3       1984-01-01 11:10:25.290
4       1984-01-01 19:38:19.790
                  ...
70793   2002-12-29 19:37:24.560
70794   2002-12-29 20:17:33.400
70795   2002-12-29 20:21:28.730
70796   2002-12-30 21:51:52.550
70797   2002-12-30 23:38:49.790
Name: newdatetime, Length: 70798, dtype: datetime64[ns]

In [27]:
earthquakes.describe()

,mag,LAT,LON,DEPTH,EVID,NPH,NGRM,newdate,newdatetime
count,70798.000000,70798.000000,70798.00000,70798.000000,7.079800e+04,70798.000000,70798.000000,70798,70798
mean,2.417826,33.977749,-116.88145,5.707677,3.699163e+06,30.424376,175.725049,1992-11-07 16:14:28.092318976,1992-11-08 04:14:59.083973376
min,2.000000,30.094830,-121.76000,0.000000,2.825500e+04,0.000000,0.000000,1984-01-01 00:00:00,1984-01-01 01:30:57.520000
25%,2.120000,33.061000,-117.69200,3.100000,7.380962e+05,15.000000,59.000000,1988-05-05 00:00:00,1988-05-05 20:49:20.964999936
50%,2.300000,34.056750,-116.59000,5.300000,3.049477e+06,24.000000,111.000000,1992-07-18 00:00:00,1992-07-18 06:27:56.530000
75%,2.590000,34.591000,-116.25100,6.900000,3.325926e+06,39.000000,211.000000,1996-10-29 00:00:00,1996-10-29 15:31:47.564999936
max,7.100000,37.985500,-113.71900,29.300000,3.736673e+07,406.000000,3815.000000,2002-12-30 00:00:00,2002-12-30 23:38:49.790000
std,0.407683,1.156586,1.07667,3.842620,3.495378e+06,22.374143,226.196774,NaN,NaN

In [28]:
earthquakes["newdatetime"].mean()

Timestamp('1992-11-08 04:14:59.083973376')

In [29]:
earthquakes["newdatetime"].std()

Timedelta('1826 days 19:14:43.046994976')

In [30]:
earthquakes["newdatetime"].diff()

0                          NaT
1       0 days 04:00:36.640000
2       0 days 01:27:30.980000
3       0 days 04:11:20.150000
4       0 days 08:27:54.500000
                 ...
70793   0 days 00:00:30.140000
70794   0 days 00:40:08.840000
70795   0 days 00:03:55.330000
70796   1 days 01:30:23.820000
70797   0 days 01:46:57.240000
Name: newdatetime, Length: 70798, dtype: timedelta64[ns]